name: CI

env:
  SONAR_SCANNER_VERSION: 5.0.1.3006

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "src/test/java/**"
      - "target/**"

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "src/test/java/**"
      - "target/**"

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run CodeScan On Push
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@cd9694
        with:
          scanChangedFilesOnly: true
          organization: cd-8508
          projectKey: 1-ghactions2
          codeScanUrl: https://preview.codescan.io/
          login: ${{ secrets.CODESCAN_TOKEN }}
          generateSarifFile: true

      - name: Run CodeScan On PR
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@cd9694
        with:
          scanChangedFilesOnly: true
          organization: cd-8508
          projectKey: 1-ghactions2
          codeScanUrl: https://preview.codescan.io/
          login: ${{ secrets.CODESCAN_TOKEN }}
          generateSarifFile: true
          args: |
            sonar.pullrequest.branch=${{ github.head_ref }}
            sonar.pullrequest.base=${{ github.base_ref }}
            sonar.pullrequest.key=${{ github.event.number }}

      - name: Check generated SARIF file
        run: |
          echo "Working directory:"
          pwd

          echo "Repository files:"
          ls -la

          echo "Searching for SARIF files:"
          find . -type f \( -name "*.sarif" -o -name "*.sarif.json" \) -print

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: codescan.sarif

      - name: Archive SARIF file
        uses: actions/upload-artifact@v4
        with:
          name: codescan-sarif
          path: codescan.sarif
